service: dash-serverless-example

variablesResolutionMode: 20210219
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

custom:
  wsgi:
    app: app.server
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**

# sources
# https://stackoverflow.com/questions/45342990/aws-lambda-error-unzipped-size-must-be-smaller-than-262144000-bytes
# https://github.com/serverless/serverless-python-requirements/issues/663
# https://github.com/99x/serverless-dynamodb-local/issues/135
# https://stackoverflow.com/questions/66845303/deploying-a-plotly-dash-app-to-aws-using-serverless-framework
# https://stackoverflow.com/questions/53220719/importerror-no-module-named-dash
# https://www.serverless.com/blog/flask-serverless-api-in-aws-lambda-the-easy-way